workflows:
  ios_appstore_manual_signing:
    name: iOS App Store (Unity Xcode, manual signing)
    max_build_duration: 60
    # instance_type: mac_mini_m2

    environment:
      groups:
        - signing            # CERTIFICATE_P12, CERTIFICATE_PASSWORD, MOBILEPROVISION
        - appstore_connect   # APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        BUNDLE_ID: io.battung.brightbins
        DEVELOPMENT_TEAM: R35GJ22D76
        SCHEME: Unity-iPhone
        CHOSEN_SCHEME: Unity-iPhone
        PROFILE_NAME: BrightBins              # имя профиля (НЕ UUID)
        EXPORT_METHOD: app-store              # корректное значение для App Store
        # Если проект не в корне — укажи путь явно (одну из строк ниже) и Unity-экспорт не понадобится:
        # XCODE_PROJECT: "Build/iOS/Unity-iPhone.xcodeproj"
        # XCODE_WORKSPACE: "MyApp.xcworkspace"

    scripts:
      - name: Git LFS (Unity бинарники)
        script: |
          set -eu
          git lfs install
          git lfs fetch
          git lfs checkout

      - name: Импорт сертификата и профиля
        script: |
          set -eu

          KEYCHAIN_NAME=codemagic.keychain
          KEYCHAIN_PASS="$(uuidgen)"
          security create-keychain -p "$KEYCHAIN_PASS" "$KEYCHAIN_NAME"
          security set-keychain-settings "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASS" "$KEYCHAIN_NAME"
          security list-keychains -d user -s "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"

          # Сертификат: путь в секрете или base64
          CERT_FILE="cert.p12"
          if [ -n "${CERTIFICATE_P12:-}" ] && [ -f "${CERTIFICATE_P12:-/dev/null}" ]; then
            CERT_FILE="$CERTIFICATE_P12"
          else
            printf "%s" "$CERTIFICATE_P12" | base64 --decode > "$CERT_FILE"
          fi
          security import "$CERT_FILE" -k "$KEYCHAIN_NAME" -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security -A
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASS" "$KEYCHAIN_NAME"
          echo "🔐 Подписи:"
          security find-identity -v -p codesigning "$KEYCHAIN_NAME" || true

          # Профиль: путь в секрете или base64 → ставим в систему
          PROF_FILE="profile.mobileprovision"
          if [ -n "${MOBILEPROVISION:-}" ] && [ -f "${MOBILEPROVISION:-/dev/null}" ]; then
            PROF_FILE="$MOBILEPROVISION"
          else
            printf "%s" "$MOBILEPROVISION" | base64 --decode > "$PROF_FILE"
          fi

          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_DIR"

          TMP_PLIST="$(mktemp -t prov.plist)"
          security cms -D -i "$PROF_FILE" > "$TMP_PLIST"

          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print UUID" "$TMP_PLIST")
          PROFILE_NAME_DETECTED=$(/usr/libexec/PlistBuddy -c "Print Name" "$TMP_PLIST" 2>/dev/null || true)
          APP_IDENTIFIER=$(/usr/libexec/PlistBuddy -c "Print Entitlements:application-identifier" "$TMP_PLIST")

          cp "$PROF_FILE" "$PROFILE_DIR/$PROFILE_UUID.mobileprovision"

          echo "export PROFILE_UUID=\"$PROFILE_UUID\"" >> "$CM_ENV"
          if [ -n "${PROFILE_NAME:-}" ]; then
            echo "export PROFILE_NAME=\"$PROFILE_NAME\"" >> "$CM_ENV"
          else
            echo "export PROFILE_NAME=\"$PROFILE_NAME_DETECTED\"" >> "$CM_ENV"
          fi

          echo "📄 PROFILE_UUID: $PROFILE_UUID"
          echo "📄 PROFILE_NAME: ${PROFILE_NAME:-$PROFILE_NAME_DETECTED}"
          echo "📄 application-identifier: $APP_IDENTIFIER"

          case "$APP_IDENTIFIER" in
            *."$BUNDLE_ID"|"$DEVELOPMENT_TEAM.$BUNDLE_ID") : ;;
            *) echo "⚠️ Похоже, профиль не для $BUNDLE_ID. Проверь тип (App Store) и bundle id." ;;
          esac

      - name: Если Xcode-проекта нет — экспортировать его из Unity (headless)
        script: |
          set -eu

          # Если явно задан workspace/project — ничего не делаем
          if [ -n "${XCODE_WORKSPACE:-}" ] || [ -n "${XCODE_PROJECT:-}" ]; then
            echo "➡️ XCODE_WORKSPACE/PROJECT уже заданы, Unity-экспорт не требуется."
            exit 0
          fi

          ROOT="${CM_REPO_DIR:-$PWD}"
          echo "📁 Repo root: $ROOT"

          # Уже есть .xcworkspace/.xcodeproj в репо?
          XW="$(find "$ROOT" -maxdepth 8 -type d -name "*.xcworkspace" -print -quit 2>/dev/null || true)"
          XP="$(find "$ROOT" -maxdepth 8 -type d -name "*.xcodeproj"   -print -quit 2>/dev/null || true)"
          if [ -n "$XW" ] || [ -n "$XP" ]; then
            echo "✅ Xcode-проект уже найден в репо, пропускаю Unity-экспорт."
            exit 0
          fi

          echo "🧩 Xcode-проект не найден. Запускаю Unity в headless, чтобы экспортировать iOS-проект…"

          # Минимальный Editor-скрипт для сборки iOS
          mkdir -p "$ROOT/Assets/Editor"
          cat > "$ROOT/Assets/Editor/CIBuilder.cs" <<'CS'
          using System.Linq;
          using System.IO;
          using UnityEditor;
          using UnityEditor.Build.Reporting;
          using UnityEngine;

          public static class CIBuilder {
              public static void PerformIOSBuild() {
                  var scenes = EditorBuildSettings.scenes
                      .Where(s => s.enabled)
                      .Select(s => s.path)
                      .ToArray();

                  if (scenes.Length == 0) {
                      throw new System.Exception("No enabled scenes in Build Settings.");
                  }

                  var buildPath = Path.Combine("Build", "iOS");
                  Directory.CreateDirectory(buildPath);

                  var report = BuildPipeline.BuildPlayer(scenes, buildPath, BuildTarget.iOS, BuildOptions.None);
                  if (report.summary.result != BuildResult.Succeeded) {
                      throw new System.Exception("iOS build failed: " + report.summary.result);
                  }
                  Debug.Log("✅ Unity exported iOS project to: " + buildPath);
              }
          }
          CS

          # Ищем Unity бинарник
          UNITY_BIN="$(ls -d /Applications/Unity/Hub/Editor/*/Unity.app/Contents/MacOS/Unity 2>/dev/null | sort -V | tail -n 1 || true)"
          if [ -z "$UNITY_BIN" ]; then
            # запасной путь
            UNITY_BIN="/Applications/Unity/Unity.app/Contents/MacOS/Unity"
          fi
          if [ ! -x "$UNITY_BIN" ]; then
            echo "❌ Unity не найден. Укажи XCODE_PROJECT вручную или установи Unity на образе."
            exit 1
          fi
          echo "🟢 Использую Unity: $UNITY_BIN"

          "$UNITY_BIN" -quit -batchmode -nographics \
            -projectPath "$ROOT" \
            -executeMethod CIBuilder.PerformIOSBuild \
            -logFile "$CM_BUILD_DIR/unity-export.log"

          # Проверяем, что Xcode-проект появился
          XP2="$(find "$ROOT/Build/iOS" -maxdepth 1 -type d -name "*.xcodeproj" -print -quit 2>/dev/null || true)"
          if [ -z "$XP2" ]; then
            echo "❌ Unity не создал .xcodeproj в Build/iOS. Смотри лог: $CM_BUILD_DIR/unity-export.log"
            exit 1
          fi

          echo "✅ Найден Xcode-проект: $XP2"
          echo "export XCODE_PROJECT=\"$XP2\"" >> "$CM_ENV"

      - name: Найти проект/воркспейс и схему (POSIX-поиск)
        script: |
          set -eu

          CHOSEN="${SCHEME:-Unity-iPhone}"
          echo "✅ Using scheme (forced): $CHOSEN"
          echo "export CHOSEN_SCHEME=\"$CHOSEN\"" >> "$CM_ENV"

          # Если путь задан вручную/получен из Unity — уважаем его
          if [ -n "${XCODE_WORKSPACE:-}" ] && [ -d "$XCODE_WORKSPACE" ]; then
            echo "Using workspace (predefined): $XCODE_WORKSPACE"
            echo "export XCODE_WORKSPACE=\"$XCODE_WORKSPACE\"" >> "$CM_ENV"
            exit 0
          fi
          if [ -n "${XCODE_PROJECT:-}" ] && [ -d "$XCODE_PROJECT" ]; then
            echo "Using project (predefined): $XCODE_PROJECT"
            echo "export XCODE_PROJECT=\"$XCODE_PROJECT\"" >> "$CM_ENV"
            exit 0
          fi

          ROOT="${CM_REPO_DIR:-$PWD}"
          echo "📁 Repo root: $ROOT"
          echo "🔎 Поиск *.xcworkspace / *.xcodeproj (до 8 уровней)…"

          XW="$(find "$ROOT" -maxdepth 8 -type d -name "*.xcworkspace" -print -quit 2>/dev/null || true)"
          XP="$(find "$ROOT" -maxdepth 8 -type d -name "*.xcodeproj"   -print -quit 2>/dev/null || true)"

          if [ -n "$XW" ]; then
            echo "✅ Workspace найден: $XW"
            echo "export XCODE_WORKSPACE=\"$XW\"" >> "$CM_ENV"
            exit 0
          fi
          if [ -n "$XP" ]; then
            echo "✅ Project найден: $XP"
            echo "export XCODE_PROJECT=\"$XP\"" >> "$CM_ENV"
            exit 0
          fi

          echo "📂 Диагностика содержимого:"
          (command -v tree >/dev/null 2>&1 && tree -L 3) || (ls -la; echo; find . -maxdepth 3 -type d -print)

          echo "❌ Не найдено ни .xcworkspace, ни .xcodeproj."
          echo "Подсказка: добавь XCODE_PROJECT/XCODE_WORKSPACE в vars или закоммить Xcode-проект."
          exit 1

      - name: Поднять номер сборки (CFBundleVersion)
        script: |
          set -eu
          INFOPLIST="$(grep -rl --include="Info.plist" "<string>${BUNDLE_ID}</string>" . || true)"
          if [ -z "$INFOPLIST" ]; then
            INFOPLIST="$(grep -rl --include="Info.plist" "<key>CFBundleIdentifier</key>" . | head -n1 || true)"
          fi
          if [ -n "$INFOPLIST" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $CM_BUILD_ID" "$INFOPLIST" 2>/dev/null || \
            /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $CM_BUILD_ID" "$INFOPLIST"
            echo "📦 CFBundleVersion => $CM_BUILD_ID"
          else
            echo "⚠️ Info.plist не найден — пропускаю"
          fi

      - name: Archive and export IPA (manual signing)
        script: |
          set -eu
          : "${DEVELOPMENT_TEAM:?Missing DEVELOPMENT_TEAM}"
          : "${BUNDLE_ID:?Missing BUNDLE_ID}"
          : "${EXPORT_METHOD:?Missing EXPORT_METHOD}"
          : "${PROFILE_NAME:?Missing PROFILE_NAME}"

          CHOSEN_SCHEME="${CHOSEN_SCHEME:-${SCHEME:-Unity-iPhone}}"
          [ -z "$CHOSEN_SCHEME" ] && { echo "❌ Нет схемы"; exit 1; }
          echo "✅ Archive will use scheme: $CHOSEN_SCHEME"

          if [ -n "${XCODE_WORKSPACE:-}" ] && [ -d "$XCODE_WORKSPACE" ]; then
            PROJ_ARG="-workspace \"$XCODE_WORKSPACE\""
            echo "Using workspace: $XCODE_WORKSPACE"
          elif [ -n "${XCODE_PROJECT:-}" ] && [ -d "$XCODE_PROJECT" ]; then
            PROJ_ARG="-project \"$XCODE_PROJECT\""
            echo "Using project: $XCODE_PROJECT"
          else
            echo "❌ Ни workspace, ни project не найдены (и не заданы в vars)."
            exit 1
          fi

          ARCHIVE_PATH="$CM_BUILD_DIR/app.xcarchive"

          # 1) Архивируем без подписи
          eval xcodebuild -resolvePackageDependencies $PROJ_ARG -scheme \""$CHOSEN_SCHEME"\"
          eval xcodebuild archive \
            $PROJ_ARG \
            -scheme \""$CHOSEN_SCHEME"\" \
            -configuration Release \
            -archivePath \""$ARCHIVE_PATH"\" \
            DEVELOPMENT_TEAM=\""$DEVELOPMENT_TEAM"\" \
            PRODUCT_BUNDLE_IDENTIFIER=\""$BUNDLE_ID"\" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
          | tee "$CM_BUILD_DIR/xcodebuild-archive.log"

          # 2) Экспорт с ручным подписанием
          mkdir -p "$CM_EXPORT_DIR"
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>${EXPORT_METHOD}</string>
            <key>teamID</key>
            <string>${DEVELOPMENT_TEAM}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>signingCertificate</key>
            <string>Apple Distribution</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${PROFILE_NAME}</string>
            </dict>
            <key>destination</key>
            <string>export</string>
            <key>compileBitcode</key>
            <false/>
            <key>uploadBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

          echo "🧾 exportOptions.plist:"; cat exportOptions.plist

          eval xcodebuild -exportArchive \
            -archivePath \""$ARCHIVE_PATH"\" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath \""$CM_EXPORT_DIR"\" \
          | tee "$CM_BUILD_DIR/xcodebuild-export.log"

    artifacts:
      - $CM_BUILD_DIR/unity-export.log
      - $CM_BUILD_DIR/xcodebuild-archive.log
      - $CM_BUILD_DIR/xcodebuild-export.log
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        # skip_waiting_for_build_processing: true
