workflows:
  ios_appstore_manual_signing:
    name: iOS App Store Manual signing (Unity Xcode export)
    max_build_duration: 60

    environment:
      groups:
        - signing
        - appstore_connect
      vars:
        BUNDLE_ID: "io.battung.brightbins"
        EXPORT_METHOD: "app-store"

    scripts:
      - name: "Git LFS (большие Unity-бинарники)"
        script: |
          set -euo pipefail
          git lfs install
          git lfs fetch
          git lfs checkout

      - name: "Импорт сертификата и профиля"
        script: |
          # (оставь как в предыдущей версии — без изменений)
          :

      - name: "Найти Xcode проект/воркспейс и схему"
        script: |
          # (оставь как в предыдущей версии — без изменений)
          :

      - name: "Manual signing только для app-таргета"
        script: |
          # (оставь как в предыдущей версии — без изменений)
          :

      # ⛔️ ВАЖНО: этот шаг мы УБРАЛИ
      # - name: "Отключить Unity IL2CPP/Bee Run Script (GameAssembly) — без Python"
      #   script: | ...
      # ---------------------------------------------

      - name: "Проверка наличия IL2CPP toolchain в проекте"
        script: |
          set -euo pipefail
          ROOT="$(pwd)"
          DEPLOY_DIR_1="$ROOT/Il2CppOutputProject/IL2CPP/build/deploy_arm64"
          DEPLOY_DIR_2="$ROOT/Il2CppOutputProject/IL2CPP/build/deploy"
          BEE_1="$DEPLOY_DIR_1/bee_backend/mac-arm64/bee_backend"
          BEE_2="$DEPLOY_DIR_2/bee_backend/mac-arm64/bee_backend"
          IL2CPP_1="$DEPLOY_DIR_1/il2cpp"
          IL2CPP_2="$DEPLOY_DIR_2/il2cpp"

          echo "Проверяю Il2CppOutputProject содержимое…"
          find Il2CppOutputProject -maxdepth 3 -type d -name "deploy*" -print || true

          if [ -x "$IL2CPP_1" ] && [ -x "$BEE_1" ]; then
            echo "OK: найдено $DEPLOY_DIR_1"
          elif [ -x "$IL2CPP_2" ] && [ -x "$BEE_2" ]; then
            echo "OK: найдено $DEPLOY_DIR_2"
          else
            echo "❌ Il2CPP/bee не найдены в репозитории."
            echo "Нужно заново экспортировать Xcode-проект из Unity и ЗАКОМИТИТЬ эти каталоги:"
            echo "  Il2CppOutputProject/IL2CPP/build/deploy_arm64  (или build/deploy)"
            echo "  Il2CppOutputProject/IL2CPP/build/bee_backend"
            echo
            echo "Подсказка по LFS:"
            echo "  git lfs track \"Il2CppOutputProject/IL2CPP/build/**\""
            echo "  git add .gitattributes Il2CppOutputProject/IL2CPP/build"
            echo "  git commit -m \"Add il2cpp deploy and bee backend\" && git push"
            exit 65
          fi

      - name: "Prepare versions"
        script: |
          # (оставь как в предыдущей версии — без изменений)
          :

      - name: "Archive and export IPA"
        script: |
          # (оставь как в предыдущей версии — без изменений)
          :

    artifacts:
      - $CM_BUILD_DIR/xcodebuild-archive.log
      - $CM_EXPORT_DIR/*.ipa
      - $CM_EXPORT_DIR/*.dSYM.zip
      - $CM_BUILD_DIR/*.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
